services:
  mssql:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    container_name: sqlserver_simulacao
    user: "10001:0"
    environment:
      SA_PASSWORD: "Senha@123admin" 
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "Senha@123admin", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10 
    restart: always
    networks:
      - simulacoes-api-net

  api:
    build:
      context: ./simulacoes-api
      dockerfile: Dockerfile
    container_name: simulacoes_api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:sqlserver://mssql:1433;encrypt=false;trustServerCertificate=true;databaseName=simulacao
      DB_USERNAME: usr_simulacao
      DB_PASSWORD: simulacao_usr
    depends_on:
      mssql:
        condition: service_healthy
    restart: on-failure
    networks:
      - simulacoes-api-net    

networks:
  simulacoes-api-net:
    driver: bridge