services:
  app:
    build:
      context: ./simulacoes-api
      dockerfile: Dockerfile
    container_name: simulacoes_api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true;databaseName=simulacao
      DB_USERNAME: sa
      DB_PASSWORD: Senha@123admin
    depends_on:
      - mssql
    restart: on-failure
    
  mssql:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    container_name: sqlserver_simulacao
    environment:
      SA_PASSWORD: "Senha@123admin" 
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
    restart: always

volumes:
  sqlserver_data: